### ISSUE TITLE
scss version

### ISSUE THREAD

**Issue by marban** [stephenhutchings/microns#6]
Could you add a scss version in order to override the path for the font src?

**Comment by stephenhutchings** [comment]
Yep that's doable.

**Comment by stephenhutchings** [comment]
@marban does something like this make sense?

```scss
$microns-font-name: "microns" !default;
$microns-font-file: "microns" !default;

@font-face {
  font-family: $microns-font-name;
  font-style: normal;
  font-weight: normal;
  src: url("#{$microns-font-file}.eot");
  src: url("#{$microns-font-file}.eot?#iefix") format("embedded-opentype"),
       url("#{$microns-font-file}.woff2") format("woff2"),
       url("#{$microns-font-file}.woff") format("woff"),
       url("#{$microns-font-file}.ttf") format("truetype"),
       url("#{$microns-font-file}.svg") format("svg");
}
```
